Major ObjC Analysis Improvments
Vector35/workflow_objc pull request #10
Opened 2022-07-29 00:34 UTC by cxnder

Official changelog:

- ObjC Processing now supports armv7+thumb binaries

- Type definition speedup

- Classes now have properly defined types

- ivars now render inline as struct members to 'self'

- off-image objc_msgSend calls now properly inline the selector string

---

devlog:

AbstractFile now has an m_ptrSize and readPointer() / readPointer(uint64_t). These are used to make supporting across 32/64 bit trivial.

TypeParser now returns a `ParsedType` object, which holds the name + std::opt<Ref<Type>> + flavor (named, struct, etc) and an unused "dependency" field, which should(?) be used later in time to do dependency resolution when we add named types.

TypeParser now requires an Ref<Architecture> object as arg0 since it is generating pointer class Ref<Type>s and needs to know the proper pointer size.

CustomTypes no longer uses ParseTypesFromSource() for several reasons. Types are now defined with the official and wonderfully documented C++ api for doing so. 

All types (except for specifically the `typedefs` detailed below) via the c++ api are now registered as system types, hiding them in the Types view by default. Perhaps even the typedefs should be hidden.

New InfoHandler::CreateClassType() which creates and registers a structure `class_ClassName` and a `typedef struct class_ClassName* ClassName`. It then registers all of the ivars into that struct using their hard coded offsets. This results in weird looking structs.

Ivar list now has its structs processed. 

All of the struct types are now defined based on the bv's address size and adjusted based on the official objc_runtime-old.h . 

In the initializing workflow pass, we now parse through all the msgSend symbols and define their type to `void *(* const _objc_msgSend)(id self, SEL sel)` which was not at all a headache to do with the C++ api. This causes all of the un-rewritten selectors to inline their sel strings, which is an insane improvement by itself.

---

Still a lot to do, but this is hopefully a good start.

~~let the bikeshedding begin~~

2022-08-01 12:16 UTC, cxnder commented
Hold off for a bit, obvious formatting issues + found a segfault.

2022-08-01 13:28 UTC, jonpalmisc commented
Created #11 to track part of this. Will see how much this address other open issues during testing and link them accordingly.

2022-09-01 12:22 UTC, plafosse requested changes

2022-09-01 12:22 UTC, plafosse commented on Core/TypeParser.h
> +    static std::vector<ParsedType> parseEncodedType(BinaryNinja::Ref<BinaryNinja::Architecture> arch, const std::string&);
Architecture objects really don't need to be reference counted as they're singleton objects.

2022-09-01 12:22 UTC, plafosse commented on Workflow.cpp
> +	const auto laSymbolPtrSection = bv->GetSectionByName("__la_symbol_ptr");
whitespace

2022-09-01 12:22 UTC, plafosse commented on Workflow.cpp
> +			|| (laSymbolPtrSection && sectionContains(laSymbolPtrSection, c))
whitespace

2022-09-01 12:22 UTC, plafosse commented on Workflow.cpp
> +					auto retType = BinaryNinja::Type::PointerType(bv->GetAddressSize(), BinaryNinja::Type::VoidType());
be careful when assigning things to `void*` you should probably set the confidence to 0

2022-09-01 12:52 UTC, jonpalmisc requested changes
# Formatting

There are plenty of formatting oddities and other issues; I believe I've left comments on all of the ones that _cannot_ be solved by `clang-format`.

The rest of the formatting inconsistencies can (and should) be solved by running `clang-format -i --style WebKit` on all sources and headers.

# Testing

The regression testing Objective Ninja formerly had was removed when it became an official plugin. I will look into adding it back in to ensure this PR doesn't introduce any unintended changes in analysis.

# Architecture

Objective Ninja was originally designed such that everything in the `Core` subdirectory had no dependency on Binary Ninja. The analysis used plain C++ and as long as you could provide your own valid implementation of `AbstractFile`, the analysis would work.

I haven't left comments on each individual violation of this, as there are numerous. One of two things would need to happen before I feel good about this being merged:

- Option A: `AbstractFile` is largely dissolved and Objective Ninja's usefulness as a backed-agnostic Objective-C analysis framework disappears.
- Option B: The changes presented here are restructured to allow the `Core` subdirectory to remain dependency-free and not be tied to Binary Ninja.

I would personally prefer Option B. In addition to retaining what I believe to be a nice quality of Objective Ninja, I also believe that having the core analysis and Binary Ninja-specific stuff separated make the code easier to reason about and helps maintain good separation of concerns.

2022-09-01 12:52 UTC, jonpalmisc commented on Core/Analyzers/ClassAnalyzer.cpp
> +		int RO_IVAR_OFF_FROM_PTR_START = RO_PTR_START + pointerSize * 4;
These should follow the normal naming convention, e.g. `roPointerStart`, `roMethodOffset`, etc, etc.

2022-09-01 12:52 UTC, jonpalmisc commented on Core/Analyzers/SelectorAnalyzer.cpp
> +
Remove this blank line

2022-09-01 12:52 UTC, jonpalmisc commented on Core/BinaryViewFile.cpp
> +	return readLong();
This can be consolidated into `if (m_ptrSize == 4) readInt()` otherwise, `readLong()`

2022-09-01 12:52 UTC, jonpalmisc commented on Core/BinaryViewFile.h
> +	uint64_t m_ptrSize;
Please change to `m_pointerSize`

2022-09-01 12:52 UTC, jonpalmisc commented on Core/AbstractFile.h
> +
`s/arch/architecture/`, wrap comments at 80 columns

2022-09-01 12:52 UTC, jonpalmisc commented on Core/AnalysisInfo.h
> +
Remove added blank line

2022-09-01 12:52 UTC, jonpalmisc commented on Core/TypeParser.cpp
> +
Remove blank line under `for` loop

2022-09-01 12:52 UTC, jonpalmisc commented on Core/TypeParser.cpp
> +			// TODO: Emit real type names.
Is this still a TODO?

2022-09-01 12:52 UTC, jonpalmisc commented on InfoHandler.cpp
> +		f->SetUserType(functionType);
Without looking too closely at what this is doing, my "need for a separate function" senses are going off. Seems to be a lot of indentation and complexity here which could benefit from either simplification or extraction into a helper function.

2022-09-01 12:52 UTC, jonpalmisc commented on InfoHandler.cpp
> +		}
Remove braces since they are not used with single-line for loops in this project.

2022-09-06 16:34 UTC, cxnder commented
Closing this in favor of reworking the structure of the changes and tracking them as several smaller improvements vs one large mega-PR

2022-09-06 16:34 UTC, closed without merging