Process Ivars, Create custom types for ObjC Classes
Vector35/workflow_objc pull request #28
Opened 2022-09-12 02:24 UTC by cxnder

Resolves #17 , Resolves #27

2022-09-12 02:29 UTC, cxnder commented on Core/AnalysisInfo.h
> + * A description of an Objective-C ivar
Punctuation

2022-09-12 02:29 UTC, cxnder commented on Core/AnalysisInfo.h
> +     * Get the method's type as series of C-style tokens.
Incorrect comment

2022-09-12 02:29 UTC, cxnder commented on Core/AnalysisInfo.h
> + * A description of an Objective-C ivar list
Punctuation

2022-09-12 02:29 UTC, cxnder commented on InfoHandler.cpp
> +#include "Core/TypeParser.h"
Why is this imported?

2022-09-12 02:29 UTC, cxnder commented on CustomTypes.h
> +const std::string IvarList = "objc_ivar_list_t";
Move this to after MethodListEntry

2022-09-12 02:34 UTC, cxnder commented
Before -> After of this PR
![image](https://user-images.githubusercontent.com/55725881/189563799-2a77740c-6642-4af0-b648-47079f460108.png)

2022-09-12 16:54 UTC, jonpalmisc requested changes
Looks good barring a handful of small code changes. I did **not** test the code itself, I'm planning to do that once these requested changes are done.

Have you tried this on really large binaries? I'll do some testing myself as well, but whenever new features are added I like to get an idea of their performance impact.

2022-09-12 16:54 UTC, jonpalmisc commented on Core/AnalysisInfo.h
> + * A description of an Objective-C ivar.
Pedantic, but: "ivar" being short for "instance variable" should be conveyed at least once somewhere in this code, even though the runtime calls them "ivars". 

In general, I think "instance variable" > "ivar" in comments at least; "ivar" in names/types is fine.

This same comment applies to the next few documentation comments.

2022-09-12 17:54 UTC, cxnder commented
> Have you tried this on really large binaries? I'll do some testing myself as well, but whenever new features are added I like to get an idea of their performance impact.

I have not. There is a small potential for slowdown in that with the current type system (which this interacts with *much* more frequently now), we are potentially invoking the clang string type parser API up to twice as often per class as we were before. That should be mitigated when #19 is handled.

2022-11-10 16:07 UTC, jonpalmisc approved these changes

2022-11-10 16:19 UTC, merged